export const THEMES = {
  light: {
    bg:        "#f4f5f7",
    bg2:       "#ffffff",
    bg3:       "#eef0f4",
    bg4:       "#e2e5eb",
    text:      "#111827",
    text2:     "#6b7280",
    text3:     "#9ca3af",
    border:    "#e5e7eb",
    border2:   "#d1d5db",
    accent:    "#2563eb",
    accentBg:  "#eff6ff",
    accentTxt: "#1d4ed8",
    danger:    "#dc2626",
    dangerBg:  "#fef2f2",
    warn:      "#d97706",
    warnBg:    "#fffbeb",
    ok:        "#16a34a",
    okBg:      "#f0fdf4",
    purple:    "#7c3aed",
    purpleBg:  "#f5f3ff",
  },
  dark: {
    bg:        "#0f1117",
    bg2:       "#1a1d27",
    bg3:       "#12151e",
    bg4:       "#21253a",
    text:      "#f1f5f9",
    text2:     "#94a3b8",
    text3:     "#64748b",
    border:    "#1e2235",
    border2:   "#2a2f48",
    accent:    "#3b82f6",
    accentBg:  "#1e3a5f",
    accentTxt: "#93c5fd",
    danger:    "#f87171",
    dangerBg:  "#3b1212",
    warn:      "#fbbf24",
    warnBg:    "#3b2800",
    ok:        "#4ade80",
    okBg:      "#052e16",
    purple:    "#a78bfa",
    purpleBg:  "#2e1065",
  },
};

export const NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard",       icon: "grid"     },
  { id: "monitoreo", label: "Monitoreo",        icon: "activity" },
  { id: "alertas",   label: "Alertas",          icon: "bell"     },
  { id: "reglas",    label: "Reglas / Firmas",  icon: "file"     },
  { id: "ml",        label: "ML / Modelo",      icon: "cpu"      },
  { id: "config",    label: "Configuración",    icon: "settings" },
];
